name: Besoccer Scraper Automation

on:
  schedule:
    - cron: '30 3 * * *' # 03:30
    - cron: '0 5 * * *'  # 05:00
    - cron: '0 9 * * *'  # 09:00

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Add Google credentials
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: echo "$GOOGLE_CREDENTIALS" > credentials.json

      - name: Run scraper
        run: npm start
